jwt:
    secret: ENC[AES256_GCM,data:DEpoTmPR8wbJcupl,iv:Vxc6ujIO2JA6Uu2X8Lfm9UObowq2EscnZ/pDxPw1+g0=,tag:nI2HHqYVRNvd8dG0joTtcQ==,type:str]
spring:
    data:
        mongodb:
            uri: ENC[AES256_GCM,data:Wvqs59+LAJgGg+cBxuhQlSXAXPEoOUiD/mniPsrvhpfs2PI+uk7eIW9dMOmzBy+Y5s83Bvn2Z0EwhTLmQDy2ChfDxysef5B2xJ/Ld9j06aPq36h6O9jDmIcvI9GxD3PscJ0/Qg==,iv:lqDxTbMddoM64VupBF/nsZPCe8YHlwZGKHd7TZGFcQg=,tag:Hu5GBwXTlevJTQ759qZBZw==,type:str]
            database: ENC[AES256_GCM,data:9XOv2CCYClQ=,iv:qA2KOi/n+AhNB5kMguxlucyr0ZdKJQZBQJlZCtBb7nc=,tag:Jjhyn3CSaQdGXOF+AUkIGg==,type:str]
server:
    port: ENC[AES256_GCM,data:3pc=,iv:WnZiBCc3jW/xfSvOf8YAjGKivxjg4GLatp9gSCCv5Is=,tag:7AXEKx9xEKGlboumQM+y0A==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eWk0QjdyV21PTFFobThS
            Ny9ySkdBNC9ENGJjRkI1MStzeW9FTzJhRHlFCldCWm5VQ09nbHNCRnllVDMvbjFC
            dG9JcjRZMFNqVXdpaFpuMDBTb1FUd2sKLS0tIDVzWGxZMWNCdng2azRHQTljeUpm
            czZDWFdjSzJjR0JJL1J0N3ZOTWlNcmMKuKD34nPJBstNH1WlNX4DyTufVohyU91I
            tFWxIbJK6uBuuR58LupeaOHQFhQNvPX+fmpKqGG2JsNPvsQL0+AUvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OU54RXV6cnJkdElGb3Z2
            blRvMHBhN3JDWU55S0dZc1puVWdjSEg3TG5BClRhTjRQa3R5ZXJoenFQRFlnT3Ns
            alhFR05aL21iN002VlowNzduZm5ueUkKLS0tIExLNERGaEJqTHhQeDV0RDRXMk1I
            UXRJcCtScmdKU01IRHgvNkJXYVBXR1UK4rN6W3k5erluN4CfWnFxsPm7Ry9+4Fkl
            47bGE3BM8kaZ41+w/uEIz2aj8PqnlG5bix6fc8SHmDpRZCGY4bB/qA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq6xtpmyzsum0fc2uk2dwda6rksp6dd8v2m654ev604d4n65cu8synu99s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Zk56dHk4ZVdSNndTSFQ5
            UnRoOEhsdEZzNEZmWGt3c2RZTjNGWlpGT1dRCmN2cjIrVTdLR01RN2E1M0Z3QWlF
            ME9nMU9wZXlKRGVsWk91QzlLRUdHOVkKLS0tIGR0ZDJKMW9mU2pzdXpmNUpucEZC
            K1E5SEdBZnlKNGh4dmZqdE16R3hIYmsK2uav0Og0m3UCxO5IAI/lUqgpDFeI+gBI
            61WmdKOebc8jXg1KIwHVBC4+UXM+ClGbYRK5pYQc9CV5OtQeH4Xw9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zfr86gs33mx2lfpc0083lweet3za5ufu0wsfqch4fe2glpdqqdsq0mjp6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucWkrZUVUV2F0alhWaVdv
            YzR3Um8yNldsN0JwYURVTzFCK1ViS0h0MkZRCmI5MUQ4bFdUaFg2K2llRzg2a1A1
            cW9pd1AyR1NNTGlQUnlzbDI3VCt2UTgKLS0tIFg2Zkk2WW90YjZ4eFM0bkQrNlFK
            eE1oTCs4TGQ5d0V1bzZ3bXRaYlZKUncKENvVmDoRapUcxmm2rXx+Hf32y6o1cyyH
            /uZ45pZT98wmfzb1aokPz3+sjs5N6ArHxk3Y0nYb3wCuBzI/jMJptQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T05:12:23Z"
    mac: ENC[AES256_GCM,data:kJZK1Z+7lGzLS68Bo7KeySDg8et5BPSwK/B/PQ9/l8ltsL/4Da6n/hU3gg/r0dJHG9Qr9p2oBd4rb7x0VQzBJLaqcPRhxUMwtmju9NAlq12RuaOZbGE0KBTwQ1lgwzhOE+byLDFJnQ/GsW6yN54Z/golZuZ0kHL85ZiNV9zdNiI=,iv:UvU5DOZpxyH77/xnoQhefEW2nAyOI13+v2+6RnbMjN4=,tag:pJ7jV9yGRTMjpVe/pU5LmQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
